# Generated by Django 6.0.1 on 2026-01-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_price_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
